# Generated by Django 4.2.1 on 2023-07-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("face_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="datetime",
            field=models.DateField(auto_now_add=True),
        ),
    ]
